services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: symfony_php
    working_dir: /var/www/app
    volumes:
      - ./app:/var/www/app
    environment:
      APP_ENV: dev

      # Xdebug
      XDEBUG_MODE: develop,debug
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=symfony74

      # DB (для докер-энва, удобно в .env.local)
      DATABASE_URL: "pgsql://app:app@postgres:5432/app?serverVersion=16&charset=utf8"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis
      - rabbitmq

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/app:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  postgres:
    image: postgres:16-alpine
    container_name: symfony_postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: symfony_redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: symfony_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: app
      RABBITMQ_DEFAULT_PASS: app
    ports:
      - "5672:5672"
      - "15672:15672" # UI
    volumes:
      - rabbit_data:/var/lib/rabbitmq

volumes:
  pg_data:
  rabbit_data:
